export { default, default as CreateSwitchable } from './functions/CreateSwitchable'
export type { default as SwitchableComponent } from './types/SwitchableComponent'
export { default as useHide } from './hooks/hide'
export { default as useHiding } from './hooks/hiding'
export { default as useRendering } from './hooks/rendering'
export type { HideFunction, ShowFunction } from './classes/SwitchableManager'