export type { default as Component } from './types/Component'
export { default as useHiding } from './hooks/hiding'
export { default, default as useSwitch } from './hooks/switch'
export type { HideFunction, ShowFunction } from './classes/SwitchableManager'
export type { SwitchableComponent } from './hooks/switch'